### ISSUE TITLE
SQL formatting with special characters

### ISSUE THREAD

**Issue by kannenberg** [Giorgi/DuckDB.NET#138] opened 2023-09-28 18:44 UTC
I'm trying to write SQL, but my table has columns with special characters in the name.

I've tried all kinds of coding, but I can't get the column name in the correct format from the other side.

I'm using .NET 7.0

Erro:

Binder Error: Referenced column "_Data In�cio" not found in FROM clause!
Candidate bindings: "tbl-3c5fad0d-c811-40d5-b151-4c927d3e5d13._Data Início"
LINE 1: SELECT "_Caso", "_Data In�cio", "_Data Fim"
                        ^
Stacktrace:

   at DuckDB.NET.Data.PreparedStatement.PrepareMultiple(DuckDBNativeConnection connection, String query, DuckDBParameterCollection parameters)
   at DuckDB.NET.Data.DuckDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at DuckDB.NET.Data.DuckDbCommand.ExecuteReader()

**Comment by Giorgi** [comment] 2023-09-28 19:02
This is probably a duplicate of https://github.com/Giorgi/DuckDB.NET/issues/134

**Comment by kannenberg** [comment] 2023-09-28 20:00
Do you have a release date for this version on Nuget?

**Comment by Giorgi** [comment] 2023-09-28 20:02
I'll release new version by the start of the next week. In the meantime you can try installing it from GitHub: https://github.com/Giorgi/DuckDB.NET/pkgs/nuget/DuckDB.NET.Data.Full

**Comment by Giorgi** [comment] 2023-10-02 14:24
I just pushed 0.9.0 to NuGet, can you check if it solves the issue?

**Comment by Giorgi** [comment] 2023-10-03 14:10
I'll close this issue, if it still doesn't work feel free to comment/reopen.

**Closed by Giorgi** 2023-10-03 14:10 UTC

**Comment by kannenberg** [comment] 2023-10-18 16:27
Thanks, 0.9.0 it solved the issue.
