### ISSUE TITLE
Still 'attempted to read or write protected memory'

### ISSUE THREAD

**Issue by brasio** [Giorgi/DuckDB.NET#217] opened 2024-09-12 15:40 UTC
I'm suddenly experiencing this problem, while opening a connection, from a standalone application (no visual studio). This problem affects only duckdb.dll 1.1.0 (the last one), the previous one was ok. I'm using last version of duckdb bindings. .net framework target is 4.7.2

**Comment by Giorgi** [comment] 2024-09-12 15:41
Can you share the code that throws that exception?

**Comment by Giorgi** [comment] 2024-09-12 15:48
I'll also need full stack trace of the exception.

**Comment by brasio** [comment] 2024-09-12 16:05
in DuckDB.NET.Native.NativeMethods.Configuration.DuckDBCreateConfig(DuckDBConfig& config)
   in DuckDB.NET.Data.Internal.ConnectionManager.GetConnectionReference(DuckDBConnectionString connectionString)
   in DuckDB.NET.Data.DuckDBConnection.Open()
      in MyProgram.FormHome.btnNew(Object sender, EventArgs e) in G:.....
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
   in System.Windows.Forms.Button.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   in System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   in System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   in System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   in System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   in MyProgram.Program.Main(String[] args) in G:\\MyProgram\MyProgram\Program.cs

**Comment by Giorgi** [comment] 2024-09-12 16:07
Please format it as code and include all exceptions details `ex.ToString()`

**Comment by Giorgi** [comment] 2024-09-13 07:30
Can you connect to the same database with DuckDB CLI?

**Comment by brasio** [comment] 2024-09-13 09:53
Yes. I can even connect with a client like dbeaver. I'm trying now from my laptop, compiling with a different version of visual studio. The executable now has no errors. I cannot understand the reason.

**Comment by Giorgi** [comment] 2024-09-13 10:05
So it works on a different computer? What are the Windows versions on these computers?

**Comment by brasio** [comment] 2024-09-13 10:17
windows 10 pro and windows 10 home (laptop) . Different CPU, visual studio 2022 both (but different update version). I can be more specific tomorrow when I will overwrite also nuget packages to be sure.

**Comment by brasio** [comment] 2024-09-13 11:07
I have now tested on my office pcs. The error still remains. I have tested on 2 different machines, one with Intel pentium G620 and another one with Xeon Gold 6246R. I get the same error on both.
My laptop (which has no error) has a Core i7-6700HQ, but my laptop is outside office network, so I don't even know if the problem is due to some network policies as well.

**Comment by Giorgi** [comment] 2024-09-13 11:09
Can you try installing the latest version of Microsoft Visual C++ Redistributable package from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 to see if that helps?

**Comment by brasio** [comment] 2024-09-13 12:17
Done, but problem still persist. I think it is related to duckdb.dll, as previous version works well even with your last bindings.

**Comment by Giorgi** [comment] 2024-09-13 12:26
Does it work if you target .Net Core instead of .Net Framework?

**Comment by brasio** [comment] 2024-09-13 13:46
I created a .Net 6.0 project and there are no errors.

**Comment by Giorgi** [comment] 2024-09-13 16:44
Are you testing with .Net Framework on your laptop?

**Comment by Giorgi** [comment] 2024-09-13 19:49
I tried .NET Framework 4.7.2 and it worked as expected on my machine.

**Comment by brasio** [comment] 2024-09-14 15:26
The problem exists only on my **office machines** (windows 10 pro, restricted network policies and restricted administrative roles, for example I cannot access windows registry editor, CPUs are Intel pentium G620 in one machine and Xeon Gold 6246R in another machine). Ado.net bindings is your last version.
This is the situation for my office machines:


|  | duckdb.dll v 1.1 | duckdb.dll previous version (0.10.3) |
| ------------- | ------------- | ------------- |
| .Net framework 4.7.2  | error  |  OK |
| .Net framework 6.0  | OK  | OK |

**Comment by Giorgi** [comment] 2024-09-14 15:34
I strongly suspect that the issue is caused by the policies applied to your computer. It could be also caused by antivirus or similar software, but I have no idea how to diagnose it or how to solve it. One more thing that I can suggest is that you install **DuckDB.NET.Data** package (note that it doesn't end with Full and doesn't include the DuckDB native library) and see what happens when you put different versions of duckdb.dll in the lib folder.

**Comment by brasio** [comment] 2024-09-16 10:22
I made other test in my offiche machine. I tested  DuckDB.NET.Data version 1.0.2  with DuckDB 1.0.0 and no errors.

I created a new .net framework 4.7.2 empty project (no other libraries) in visual studio with DuckDB.NET.Data version 1.0.2 with DuckDB 1.1.0 and no errors. 
**I suspect that DuckDB.NET.Data version 1.0.2 with DuckDB 1.1.0 gives error in my original project (not empty one) due to some memory conflict with other libraries used in the project.** In fact I get no errors with all empty project I made (also .Net 6.0 was an empty project).

This conflict does not exixts in DuckDB 1.1.0 dll itself, because I get no errors in CLI.

Anyway, DuckDB.NET.Data full or not, for me there is no difference as I have always put duckdb.dll manually inside bin folder. In fact I noticed that using framework 4.7.2 requires me to put it manually, even if I use full package, as it does not put duckdb.dll automatically in the right folder

**Comment by Giorgi** [comment] 2024-09-16 15:58
So it works in a new project but not in the original one?

**Comment by brasio** [comment] 2024-09-17 09:50
I have replicated the issue. Following code gives my error. The application is a window forms application, .net framework 4.7.2. button1_Click gives error, while button2_Click is OK. It seems that opening a dialog creates the issue, and only for duckdb.dll v. 1.1.0 (the last one)

```
private void button1_Click(object sender, EventArgs e)
{
    DialogResult result = saveFileDialog1.ShowDialog();
    if (result == DialogResult.OK)
    {
        var duckDBConnection = new DuckDBConnection("Data Source=" + saveFileDialog1.FileName);
        try
        {
            duckDBConnection.Open(); // error
            duckDBConnection.Close();
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message);
        }
    }
}

private void button2_Click(object sender, EventArgs e)
{
        var duckDBConnection = new DuckDBConnection("Data Source=mydb.db");
        try
        {
            duckDBConnection.Open(); // OK
            duckDBConnection.Close();
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message);
        }
}
```

**Comment by brasio** [comment] 2024-09-18 13:08
CheckPathExists is set to true. Anyway, it is useful form me to owerwrite existing files. As regarding dispose, I forgot it in my code (in the original code I have a wrapper class which does all this stuff), but the errors already appears in my test code at first open() call. It does not appear with duckdb.dll v. 0.10.3 (the previous one), and **the code is the same**.
I found on the web that OpenFileDialog and SaveFiledialog loads a large amount of unmanaged code into the process, resulting in thisk kind of error.

**Comment by Giorgi** [comment] 2024-09-18 13:45
I think there isn't much I can do about it so I'm going to close it.

**Closed by Giorgi** 2024-09-18 13:45 UTC

**Comment by brasio** [comment] 2024-09-18 13:59
I think that is something related to different version of vc++ runtime libraries used by your bindings and the default window forms application, but I cannot find a solution.

**Comment by brasio** [comment] 2024-09-19 15:50
I found that the problem was due to a not recent version of Microsoft Visual C++ Redistributable which was used as the default runtime in my system. Changing it in the environmental variable was the solution. Is there any statically linked dll you provide anyway?
Thanks

**Comment by Giorgi** [comment] 2024-09-19 15:57
It will be fixed in DuckDB 1.1.1 See the PR: https://github.com/duckdb/duckdb/pull/13883

**Comment by Giorgi** [comment] 2024-09-24 09:19
@brasio Just pushed 1.1.1 to the NuGet.

**Comment by brasio** [comment] 2024-10-11 09:11
I see, thanks
